[package]
name = "voxon"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
wgpu = "25.0.2"
winit = "0.30.11"
lina = { path = "../lina" }
graphic = { path = "../graphic" }
quaternion = { path = "../quaternion" }
